### ISSUE TITLE
Sycret return n_values + 1 primitives instead of n_values

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/sycret#1]
## Description
There is 1 extra primitive that is returned at each call

## How to Reproduce
```python

import syft as sy
import torch as th

hook = sy.TorchHook(th)
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
james = sy.VirtualWorker(hook, id="james")
crypto_provider = james
torch = th
me = sy.local_worker
workers = [alice, bob]

me.crypto_store.provide_primitives("fss_comp", kwargs_={}, workers=[alice, bob], n_instances=427)
print(alice.crypto_store.fss_comp[0].shape[0]) 
```
```
428
```

## System Information
 - PySyft 0.2.9

**Comment by tholop** [comment]
Thanks for the issue! The first line is actually not an FFS, but the AES keys used in MMO to generate the rest of the array. So Rust will interpret these 428 lines as 427 primitives. 

I think it will be neater to just hardcode these MMO keys, otherwise the shape is indeed confusing :)

**Comment by LaRiffle** [comment]
haha yeah I didn't update this issue but I found indeed that this line was used to smthg else!
Yeah we would probably hardcode them, according to what David said

**Comment by tholop** [comment]
Fixed by https://github.com/OpenMined/sycret/commit/368276c2687462a9f00496771f102e84428fb74e!
