### ISSUE TITLE
Attend Clippy warnings

### ISSUE THREAD

**Issue by arturomf94** [OpenMined/sycret#35]
## Description
There are currently many warnings from clippy if we run something like:

```bash
cargo clippy --all-features --all-targets
```
We should make the pertinent changes to attend them and readjust the GitHub Action workflow to fail on warnings and errors.

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
.

**Comment by danielorihuela** [comment]
Did you do any research on how to make the CI/CD fail on clippy warnings? Or I can go ahead?

**Comment by arturomf94** [comment]
We already had that implemented before but was temporarily disabled because we had too many warnings. So it should be no problem to enable it again.

**Comment by arturomf94** [comment]
For more info, see [this commit](https://github.com/OpenMined/sycret/commit/12f3a66c7fa8c907bf9854d12fbde667a938be83#diff-a85a9e0c508de8a571c10d27dfcf1e903075cef27fd4d7216affeb90cabf8978).

**Comment by arturomf94** [comment]
We just need to set `args: --all-features --all-targets -- -D warnings` again.

**Comment by danielorihuela** [comment]
Aaaaah, okey. I though that it was like a new feature. Then I think is better that you reapply it once the other PR is merged. That way it will be faster.

**Comment by tholop** [comment]
I just merged PR #36! @arturomf94 feel free to commit the change for the warnings on master directly if you want
