### ISSUE TITLE
Update Maturin version

### ISSUE THREAD

**Issue by arturomf94** [OpenMined/sycret#39]

**Comment by tholop** [comment]
I closed #41, but if you want we can keep this issue open to remember to check Maturin from time to time.

**Comment by arturomf94** [comment]
Sweet - thanks @tholop!

**Comment by messense** [comment]
maturin 0.11.4 is out: https://github.com/PyO3/maturin/releases/tag/v0.11.4

**Comment by arturomf94** [comment]
Thank you @messense! That was quick! I think we could probably update it to that @tholop! What do you think?

**Comment by tholop** [comment]
Why not @arturomf94, feel free to reopen and auto-merge the PR!
