### ISSUE TITLE
Add Rust code benchmarks

### ISSUE THREAD

**Issue by tholop** [OpenMined/sycret#8]
## Description
Set up a standard benchmarking process for the Rust primitives. I'm not sure what would be best for us:
- Standard Rust benchmarks
- Criterion? 

## Type of Test
**Performance test** (benchmark)
- Keygen/Eval
  + For DPF and DIF
  + For single keys and for batches of keys
- PRG

Note: it can be interesting to set up some profiling too if it is not intrusive (e.g. with Flame).

## Expected Behavior
At least a few benchmarks that are easy to trigger (e.g. `cargo bench`), ideally integrated as a Github workflow.
We can extend the coverage later :slightly_smiling_face:

**Comment by arturomf94** [comment]
I think this can be closed via #32 right @tholop?

**Comment by tholop** [comment]
Yes, thanks @arturomf94!
